name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compilation & Style
      id: compilation-style
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compilation & Style
        setup-command: ''
        command: javac Main.java
        timeout: 2
        max-score: 10
    - name: Prueba de compilacion
      id: prueba-de-compilacion
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Prueba de compilacion
        setup-command: ''
        command: javac *.java
        timeout: 2
        max-score: 10
    - name: Checkstyle
      id: checkstyle
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Checkstyle
        setup-command: ''
        command: "```bash curl -L https://www.google.com/search?q=https://github.com/checkstyle/checkstyle/releases/download/releas_10.12.4/checkstyle-10.12.4-all.jar
          -o checkstyle.jar && java -jar checkstyle.jar -c /google_checks.xml *.java"
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILATION-STYLE_RESULTS: "${{steps.compilation-style.outputs.result}}"
        PRUEBA-DE-COMPILACION_RESULTS: "${{steps.prueba-de-compilacion.outputs.result}}"
        CHECKSTYLE_RESULTS: "${{steps.checkstyle.outputs.result}}"
      with:
        runners: compilation-style,prueba-de-compilacion,checkstyle
